/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OMnieRouteImport } from './routes/o-mnie'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'

const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OMnieRoute = OMnieRouteImport.update({
  id: '/o-mnie',
  path: '/o-mnie',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mnie': typeof OMnieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mnie': typeof OMnieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mnie': typeof OMnieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/o-mnie' | '/sitemap.xml' | '/uslugi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/o-mnie' | '/sitemap.xml' | '/uslugi'
  id: '__root__' | '/' | '/kontakt' | '/o-mnie' | '/sitemap.xml' | '/uslugi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  OMnieRoute: typeof OMnieRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UslugiRoute: typeof UslugiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mnie': {
      id: '/o-mnie'
      path: '/o-mnie'
      fullPath: '/o-mnie'
      preLoaderRoute: typeof OMnieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  OMnieRoute: OMnieRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UslugiRoute: UslugiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
